from enum import Enum


class InputSource(str, Enum):
    SEED = "seed"
    AUDIENCE = "audience"


class ContextFrontend(str, Enum):
    THOUGHT = "thought"
    PROMPT = "prompt"
    DECREE = "decree"


class GSODAttribute(str, Enum):
    REPRESENTATION = "REPRESENTATION"
    RIGHTS = "RIGHTS"
    RULE_OF_LAW = "RULE_OF_LAW"
    PARTICIPATION = "PARTICIPATION"


class GSODTrait(str, Enum):
    CREDIBLE_ELECTIONS = "CREDIBLE_ELECTIONS"
    INCLUSIVE_SUFFRAGE = "INCLUSIVE_SUFFRAGE"
    FREE_POLITICAL_PARTIES = "FREE_POLITICAL_PARTIES"
    ELECTED_GOVERNMENT = "ELECTED_GOVERNMENT"
    EFFECTIVE_PARLIAMENT = "EFFECTIVE_PARLIAMENT"
    LOCAL_DEMOCRACY = "LOCAL_DEMOCRACY"

    ACCESS_TO_JUSTICE = "ACCESS_TO_JUSTICE"
    CIVIL_LIBERTIES = "CIVIL_LIBERTIES"
    BASIC_WELFARE = "BASIC_WELFARE"
    POLITICAL_EQUALITY = "POLITICAL_EQUALITY"

    JUDICIAL_INDEPENDENCE = "JUDICIAL_INDEPENDENCE"
    ABSENCE_OF_CORRUPTION = "ABSENCE_OF_CORRUPTION"
    PREDICTABLE_ENFORCEMENT = "PREDICTABLE_ENFORCEMENT"
    PERSONAL_INTEGRITY_AND_SECURITY = "PERSONAL_INTEGRITY_AND_SECURITY"

    CIVIL_SOCIETY = "CIVIL_SOCIETY"
    CIVIC_ENGAGEMENT = "CIVIC_ENGAGEMENT"
    ELECTORAL_PARTICIPATION = "ELECTORAL_PARTICIPATION"


class GinkgoMessageType(str, Enum):
    INPUT = "INPUT"
    KEYSTROKE = "KEYSTROKE"
